import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useCurrentUser } from "../src/hooks/auth/useCurrentUser";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { user: currentUser } = useCurrentUser();

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS JWT Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js JWT Auth!</a>
        </h1>

        <p className={styles.description}>
          {currentUser
            ? `Hello ${currentUser.username}`
            : "You are not logged in !"}
        </p>

        <div className={styles.grid}>
          <Link href="/about" className={styles.card}>
            <h2>About Page &rarr;</h2>
            <p>This is a public route for every user!</p>
          </Link>

          <Link href="/login" className={styles.card}>
            <h2>Login Page &rarr;</h2>
            <p>This is a private route for unauthenticated user!</p>
          </Link>

          <Link href="/profile" className={styles.card}>
            <h2>Profile Page &rarr;</h2>
            <p>This is a private route for authenticated user!</p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </Link>
      </footer>
    </div>
  );
}
